### ISSUE TITLE
Datepicker version 1.6.1 stops jQuery 2.2.x

### ISSUE THREAD

**Issue by getamach** [uxsolutions/bootstrap-datepicker#1899]
Working fine with jQuery 2.1.x version. When jQuery was upgraded to 2.2.x, when we call datepicker function, jQuery stops showing error 
Error is: View is null

Error comes from jQuery, not from bootstrap-datepicker.js

**Comment by acrobat** [comment]
Can you provide (as the issue template suggests) a jsfiddle example to show the issue? (I can't reproduce)

**Comment by albertotn** [comment]
hi!
Here an example for this behavior on Firefox 47.0 and Chrome 51.0

https://jsfiddle.net/sx49tcjx/1/

please see console for following error:

> SyntaxError: expected expression, got '.' bootstrap-datepicker.css:8:0
> TypeError: $(...).datepicker is not a function
